"""Generate the six Bonsai PQ2 programs and embed their MIL and constants."""
import argparse
import json
import math
from pathlib import Path
import subprocess
import sys

parser = argparse.ArgumentParser()
parser.add_argument("--output", type=Path, required=True)
parser.add_argument("--models", type=Path, required=True)
parser.add_argument("--fraction", type=float, default=0.65)
args = parser.parse_args()
if not math.isfinite(args.fraction) or not 0 < args.fraction <= 1:
    parser.error("--fraction must be greater than zero and at most one")

shapes = {5120: [17408, 10240, 6144, 12288], 6144: [5120], 17408: [5120]}
programs = []
for width, outputs in shapes.items():
    rows = sorted({int(n * args.fraction / 256) * 256 for n in outputs})
    if not all(rows):
        parser.error("--fraction produces an empty ANE row partition")
    subprocess.run([
        sys.executable, str(Path(__file__).with_name("generate.py")),
        "--output", str(args.models), "--rows", *map(str, rows),
        "--widths", str(width), "--tokens", "2048",
        "--chunk-k", "2048" if width == 5120 else "1024",
    ], check=True)
    programs.extend(f"pq2_k{width}_r{r}_t2048" for r in rows)

lines = [
    "// Generated by ane-kernel/embed.py.",
    "#pragma once",
    "#include <stddef.h>",
    f"#define GGML_METAL_ANE_DEFAULT_FRACTION {args.fraction!r}",
    "struct ggml_metal_ane_resource {",
    "    const char * program;",
    "    const char * path;",
    "    const unsigned char * data;",
    "    size_t size;",
    "};",
]
entries = []
for program in programs:
    directory = args.models / (program + ".mlmodelc")
    files = [directory / "model.mil"]
    files += sorted(p for p in (directory / "weights").rglob("*") if p.is_file())
    for path in files:
        data = path.read_bytes()
        symbol = f"ggml_metal_ane_data_{len(entries)}"
        lines.append(f"static const unsigned char {symbol}[] = {{")
        for start in range(0, len(data), 16):
            lines.append("    " + ", ".join(f"0x{b:02x}" for b in data[start:start+16]) + ",")
        lines.append("    0x00\n};")
        entries.append(f"    {{{json.dumps(program)}, {json.dumps(path.relative_to(directory).as_posix())}, {symbol}, {len(data)}}},")
lines += ["static const struct ggml_metal_ane_resource ggml_metal_ane_resources[] = {"]
lines += entries + ["};", ""]
args.output.parent.mkdir(parents=True, exist_ok=True)
temporary = args.output.with_suffix(".tmp")
temporary.write_text("\n".join(lines))
temporary.replace(args.output)
print(f"Embedded {len(programs)} ANE programs in {args.output}", flush=True)
